apiVersion: batch/v1
kind: Job
metadata:
  name: s3-echoer
spec:
  template:
    spec:
      serviceAccountName: s3-echoer
      containers:
      - name: main
        image: "amazon/aws-cli" 
        command:
        - "sh"
        - "-c"
        - |
          while true; do
            time=$(date +%s)
            echo "hello $time" > bucket-$time.txt
            aws s3 cp bucket-$time.txt s3://output-bucket-s3-echoer-SUFFIX
            sleep 600
          done
        env:
        - name: AWS_DEFAULT_REGION
          value: "AWS_REGION_PLACEHOLDER"
        - name: ENABLE_IRP
          value: "true"
      restartPolicy: Never
